[tool.poetry]
name = "django_docker"
version = "0.1.0"
description = ""
authors = ["Yeojin Kim"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
